### ISSUE TITLE
Initialize NORSE with numerical distribution

### ISSUE THREAD

**Issue by olaszsoma** [hoppe93/NORSE#4] opened 2018-10-17 12:51 UTC
As stated in the title, we would like to modify the NORSE code to be able to use a given numerical distribution as an initial distribution andand do calculations with this distribution.

**Comment by olaszsoma** [comment] 2018-10-19 12:56
We would like to modify the initialDistribuiton property of the NORSE object in a way, that it accepts an external distribution, provided that this distribution has the same grid structure as NORSE. It would check if the grid is suitable for NORSE running, and if not it would give a warning/error. This feature would be incorporated into the Initialize function, where the program gives the initial distribution to the NORSE object, possibly as a separate case of the property. Do you think this can be achieved with the current NORSE program structure?

**Comment by hoppe93** [comment] 2018-10-19 13:12
I think something like that should be possible to incorporate into NORSE without changing anything outside of ``@NORSE/Initialize.m``. I would suggest a similar, but slightly different approach for the implementation though:

In ``Initialize.m``, add three optional arguments (external p, xi and f -- probably using ``varargin``) to the ``Initiialize()`` method and add a fourth option for the ``initialDistribution`` property. This option would tell NORSE to take the given p/xi/f and interpolate onto the grid that has already been constructed internally. Interpolation should be straightforward with Matlab's ``interp2`` function.

The reasons I prefer interpolation over error-checking are
- It allows restarting NORSE with new grids but keeping the distribution (and even if we don't need this feature now, it will be useful in the future)
- Taking the distribution out of NORSE risks creating truncation errors which, with the error-check approach, would cause NORSE to stop.

Let me know if I should provide more details :)

**Comment by olaszsoma** [comment] 2018-11-19 14:48
That sounded a good idea to me, but it turns out, that we cannot use interpolation. We are planning to use NORSE in another, bigger loop and interpolation may cause problems if the distribution change in the internal NORSE run is small. So it turns out, that we have to take in an external grid afterall.
First, I am going to try to give a former NORSE run distribution back to the program. Hopefully this will work easily, and we will see afterwards, how it goes.

**Comment by hoppe93** [comment] 2018-11-20 08:49
Okay, so if I understand you correctly, you also want to give NORSE an arbitrary grid to run on? You would still want to initialize NORSE with an arbitrary distribution function however, so I think my previous suggestions remain (I think any external distribution should be interpolated when we put it in NORSE, even if we expect the grid to match perfectly).

At the moment, NORSE cannot take an arbitrary grid specification as input, and I'm not sure how easy it would be to implement that functionality. The problem is that in addition to the p-xi grid, NORSE also needs corresponding first and second derivative "grids", which need to be computed with as high accuracy as possible. You're welcome to try it though, and I would be interested in hearing how it goes :)

**Comment by olaszsoma** [comment] 2018-11-20 10:07
No, we do not want to give NORSE an arbitrary grid. We would like to give an external grid, which is exactly the same as a NORSE grid. (I am aware that there are several choices of grid structure inside NORSE, we will probably just use the default.) There should be no problem giving NORSE a grid which is the same as an internal one, right? For example running the NORSE once, and than run it again (from the beginning, not continuing the calculation) by giving the resulting distribution from the previous run as an external distribution. The grid should be the same, as it was produced using NORSE so that should be a good test.
And so if the grids are the same, there should be no need for interpolation. We have to give an external grid and distribution, because the distribution we want to evolve in time using NORSE stores data in a database, where other programs can access it if needed.
Regarding the derivative "grids". Do you think that it should be enough to give the original, "0th derivative" external grid (which is the same as an internal NORSE grid) to NORSE, and then it can compute the derivative "grids"from it?

**Comment by hoppe93** [comment] 2018-11-20 10:57
So, my point about the distribution function is that if we want to initialize NORSE with an external distribution function, then we *should* use interpolation, because in the general case (which is always wise to prepare for, and in this case not very tricky to implement) we cannot expect the grid to be the same. We could implement a hacky solution which assumes the grid of the external distribution to be the same as the internal NORSE grid, but I would prefer if we didn't.

I'm still a bit confused when you talk about an "external grid", but I think I understand what you're saying now. I think that for your purposes, as you describe, you will only need to store the distribution function between NORSE runs. Then you would initialize the next NORSE object as usual, by specifying the grid *mode*, and not the grid *vector* (which is what I think of when hearing "external grid").

**Comment by olaszsoma** [comment] 2018-11-21 13:34
It might have been confusing a little what I have been talking about, that is because I was not sure either how are we planning to save the distribution and the grid between NORSE runs.

We decided that we would give NORSE 3 input parameters, from which it could work out everything we need. First we would give it a distribution function, in the same form as the NORSE class property f (probably just one column corresponding to one time step). We would also give two vectors, corresponding to pBig and xiBig. From the latter two, it should be possible to initialize a grid, is it not? This is based on the fact that in PerformCalculation.m script, there is an option for using an existing grid object to create a grid for the NORSE object. We would somehow recreate the necessary parameters for grid initialization (like nP or nXi for instance) from pBig and xiBig, and then create the Grid object using InitializeGrid method of the grid class.
Next we would check if the pBig and xiBig vectors resulting in the initialization are the same as the input vectors. If they are, then we would simply overwrite the NORSE distribution function f, and run a calculation.
Also we would check if the dimensions are correct, and also if f, pBig and xiBig has values only in the appropriate limits for each (e.g. positive only for f), before putting them in NORSE. If everything is fine, we would save the pBig and xiBig vectors in the end of the calculations and the last column of f (which is the distribution in the last time step). 

If the initialization creates different pBig and xiBig vectors than the input, then we could interpolate.
I hope it is clear what are we trying to do here. Do you think this is a possible approach? Probably other properties of the NORSE object would be given externally as well (like EHat and other physical parameters), but I have not really checked these.

**Comment by hoppe93** [comment] 2018-11-21 18:24
Okay, now I think I understand. I still stand by my suggestion though ;)

The option to "initialize with an existing grid" you see in ``PerformCalculation.m`` does not work the way we would need to. The method takes one parameter which is a flag. The flag basically indicates whether or not the NORSE object has already been initialized with a ``Grid`` object or not. If the flag is ``0``, a completely new Grid *object* is created. It doesn't take the actual grid as input.

Unfortunately it is not possible to initialize a Grid object with custom pBig and xiBig vectors at the moment, so it would not be straightforward to adapt ``PerformCalculation()`` for this. The object has to be initialized by specifying ``nP``, ``nXi``, ``pMax``, ``pGridMode`` and ``xiGridMode``; that's it. The reason for this is what I described in one of my previous posts here.

As far as I can tell, you don't actually need to assign the external grid to the NORSE object though. Taking p and xi vectors (or pBig and xiBig vectors) as input to ``Initialize()``, along with the distribution, and then interpolating, should work just as well.

**Comment by olaszsoma** [comment] 2018-11-22 10:33
Don't get me wrong, I really liked the idea of interpolating, because I found it rather straightforward, but due to numerical reasons it would be ideal if we could solve the input without it. I am quite sure I understand why this is, but probably Gergő could explain it better.

We have been trying to understand what "initialize with an existing grid" does yesterday, and got to the same conclusion, namely that it just sets up a grid with the given parameters, doesn't matter if we give a grid or not. I have been playing with that bit yesterday, and found that I can actually give an empty grid object to it (or a non-empty, it doesn't matter), and if the NORSE object has the necessary parameters determined (`nP`, `nXi`, `pMax`, `pGridMode` and `xiGridMode`) it creates the grid of NORSE. But this is what the other option does anyway, so no real big difference between the two methods.

I see that we cannot initialize grids with `pBig` and `xiBig`, but we can get `nP`, `nXi` and `pMax` from them (rather easily, I found yesterday). I guess technically we could get the modes as well (I am not sure how or if, but since they have been used to make the vectors, it should be possible, is it not?), but it might be easier to save those as well from the previous NORSE run, and give it back to the next (assuming the grid does not change between runs). Also, an initialized NORSE object has default `pGridMode` and `xiGridMode`, so if we use the default modes, we don't even have to worry about those. I am still not sure how the external database stores the grid (due to reasons beyond my reach at the moment), or what kind of grids it can take (uniform, non-unifrom, etc.). I will assume now that it can use vectors like `pBig` and `xiBig` to construct the grid of the distribution.

Assigning external grid to NORSE would only happen through `pBig` and `xiBig` if everything goes as I hope. So all information of the grid would be transferred between NORSE and the external database 'via' these vectors (and maybe, somehow via the `pGridMode` and `xiGridMode`, I am not sure about that, until I know more).

**Comment by hoppe93** [comment] 2018-11-22 16:09
Which numerical reasons? If the given distribution is given on *exactly* the same grid, the interpolation will return the exact same distribution. If it isn't, then we get whatever accuracy is availabel. But is it related to ETS rather? @gergopokol perhaps you would be able to explain?

Also, I understand that interpolation probably wouldn't be necessary for your specific applications, but in the general case (which we should strive to build NORSE for) it would be a useful feature.

Yes, the grid modes are accessible as properties on the grid object. E.g. ``oNorse.grid.pGridMode`` should give you the ``pGridMode`` variable.

I'm sorry for being such a pain about this. Maybe a discussion via Skype could help bring some clarity to all of this? If you think so too, then just send me an email and we can set a date.

**Comment by olaszsoma** [comment] 2018-11-23 09:30
I'll let Gergő to explain the problem with interpolation for now, but yeah, the problem is somehow with the fact that it is going to be ETS. I could try to explain, but I am not sure I could get a cleear and coherent description about it.

That is why we would add an option for the interpolation in case the grid is not the same. Probably it is a bit complicated to have tow separate cases, but I will go with this now, and we can change it later if needed.

I wouldn't say you are a pain about this, I actually find your remarks rather useful, thanks about tose again :D. A Skype might be  a good idea sometime, although I got this for now, I think. I'll let you know if I think it would be useful.

**Comment by olaszsoma** [comment] 2018-11-30 12:45
I have managed to modify the code in a way that it accepts external distribution as an input. I wanted to improve this by adding some sanity checks on the external inputs (such as `f`, `pBig`, `xiBig`). On the distribution it would have been checking if any of the values are negative, since that has no physical meaning. Before implementing, I checked if the the expected value, namely outputAdvanced.mat or the calculated distribution of the NORSE object has any negative values. I have found that they do, plenty, actually (very small, like ~e-40 or even e-50, but still negative). Do your calculations have these as well? And if so, is this coming from a necessity, or just a bug? We were thinking with Gergő, that probably we will just replace these values with zeros, but it might cause some problems with matrix calculations (I didn't check), so I thought double check this with you first.

**Comment by hoppe93** [comment] 2018-11-30 13:13
Yes, due to fundamental properties of the operators implemented in NORSE, the distribution function may take negative values in certain points. This is usually not a problem though, since if your resolution parameters are set high enough, the negative values will not impact the calculation. And, of course, the value of the distribution function in those points is unphysical.

Setting the negative values to zero comes with a few caveats though: by changing the value of the distribution function, you effectively add/remove particles from the distribution. If the values you change are ~e-40, this should of course not matter, but it is not uncommon to get significantly larger negative parts, and then you might have to correspondingly modify other quantities to account for this density change. Unless it is absolutely necessary to have a strictly positive distribution outside of NORSE, I would advise against enforcing positivity by setting the negative parts of the distribution to 0.

**Comment by olaszsoma** [comment] 2018-12-10 11:59
I have pushed my modifications to the NORSE code into the feature-init-distr branch. This is not nearly fully done, but it is working at the moment. I also have created an example file, which makes it possible to test the new parts of the code. I am going to attach these to this comment, along with the two saved variables I used as external grid. Please feel free to have a look what I have done and make recommendations for improvement.

The external grids are NORSE grids (the big vectors) taken from an AdvancedNORSERun calculations, with `pGridMode` and `xiGridMode` are being 1, and `gridParameter` is 0.2.  At the moment, the grid modes of the external grid are not fully calculated, only the `pGridMode` if the grid is polynomial in p. That is going to be extended to all cases both in p and xi. Also, the `gridParameter` is calculated, but is not exactly the same as the one used to create the external grid. There is about e-16 difference between the two, I plan to put some error check on that as well. As an external distribution, outputAdvanced.mat is used.

The mentioned files are uploaded as .zip, as github didn't support matlab files.
[NORSE example.zip](https://github.com/hoppe93/NORSE/files/2663027/NORSE.example.zip)

**Comment by olaszsoma** [comment] 2018-12-19 09:21
I upload the latest version of the example file, I did some minor changes to it since the last update.

[externalNORSERun.zip](https://github.com/hoppe93/NORSE/files/2694095/externalNORSERun.zip)

**Comment by olaszsoma** [comment] 2020-04-23 13:59
I have implemented interpolation for the case when the external grid is not identical to the grid initialized by NORSE. I have tested it using the attached scripts: externalNORSERun.m was run, using the input variables in input.mat.
[NORSE_test_files.zip](https://github.com/hoppe93/NORSE/files/4522915/NORSE_test_files.zip)

**Comment by gergopokol** [comment] 2020-04-27 21:18
Merged to master and in use.

**Closed as completed by gergopokol** 2020-04-27 21:18 UTC
